[theme]
# Primary accent color for interactive elements.
primaryColor = "#ffffff"

# Background color for the main content area.
backgroundColor = "#000000"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#8d99ae"

# Color used for almost all text.
textColor = "#ffffff"